steps:
- uses: actions/checkout@v2
- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    version: '306.0.0'
    project_id: 'chetz-playground'
    service_account_key: ${{ secrets.GCP_SA_KEY }}
    export_default_credentials: true
- run: gcloud info
